services:
  bucky:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bucky
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  bucky-data:
    driver: local
  bucky-logs:
    driver: local